import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import logo from '../public/img/jv-learning-logo.png';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to JV-LEARNING!</h1>

        <Image src={logo} alt="Picture of the author" width={500} height={500} />

        <div className={styles.grid}>
          <a href="https://jv-learning.com/" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Find all resources you need to become a developer</p>
          </a>

          <a href="https://jv-learning.com/" className={styles.card}>
            <h2>Design &rarr;</h2>
            <p>Apply the concepts you have learnt planning and designing your projects</p>
          </a>

          <a href="https://jv-learning.com/" className={styles.card}>
            <h2>Code &rarr;</h2>
            <p>Get down to business!</p>
          </a>

          <a href="https://jv-learning.com/" className={styles.card}>
            <h2>Repeat &rarr;</h2>
            <p>Done? Let's do it again!</p>
          </a>
        </div>
      </main>
    </div>
  );
}
